import { TryCatch } from "../middlewares/error.js";
import { ErrorHandler } from "../utils/utility.js";

export const auth = TryCatch(async (req, res, next) => {});
